<?php
/**
 * Copyright © 2015 shopcommerce. All rights reserved.
 */
?>
<?php
/**
 * {{controller}} {{action}} template
 *
 * @var $block \Shop\News\Block\Index\News
 */
?>

<?php echo $this->getChildHtml('shop_news_child'); ?>

<a href="javascript:void(0)" id="news-ajax-link">News Ajax Link</a>

<script>
    require(['jquery'], function($){
        $(document).ready(function() {
            $("#news-ajax-link").click(function() {
                $.post(
                    'news/index/ajax',

                    {
                        "message": "message text"
                    },

                    function(data) {
                        console.log(data);
                    },

                    'json'
                );
            });
        });
    });
</script>